# Generated by Django 4.2.1 on 2023-05-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
    ]
